### ISSUE TITLE
Following the "Build" Instructions

### ISSUE THREAD

**Issue by jabowery** [aquametalabs/aquameta#1]
Following the "Build" Instructions:

>* Starting PostgreSQL 9.4 database server                                                                                                                                >[ OK ] 
>root@jabowery-H61M-S2-B3:~# exit
>jabowery@jabowery-H61M-S2-B3:~/dev/aquameta$ ./build.sh
>Creating database ...
>createdb: could not connect to database template1: FATAL:  role "jabowery" does not exist

OK, so now I'm in the weeds.  I won't even bother trying to explain what happened when I tried to get out of the weeds.

PS:  Yes I know the Markdown for blockquote didn't work above and I couldn't figure out why not.

**Comment by erichanson** [comment]
Aha.  You have to run the build script as a user who has superuser access
to the database.  Try this:

sudo -iu postgres
psql
CREATE ROLE jabowery SUPERUSER LOGIN;

Then run build.sh again as your jabowery.

I'll update the build instructions.

Thanks,
Eric

**Comment by erichanson** [comment]
README.md updated.

https://github.com/aquametalabs/aquameta/commit/0c0e7bb519a6c8e8a05e3d89d3fb34f9647652ba#diff-04c6e90faac2675aa89e2176d2eec7d8
