### ISSUE TITLE
events refactor

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#14]
Refactor events to use meta.row_id, meta.relation_id and meta.column instead of deprecated selectors.

**Comment by erichanson** [comment]
Changes needed to branch event_refactor at commit https://github.com/aquametalabs/aquameta/commit/0a5f0afcb46f2a672d5b1b7ad90ed452b7448c36:

- remove session.connection
- add session_id to subscription view
- insert events into the event table from table triggers
- on session_attach(), send all events in the event table for this session (because they haven't yet been deleted aka recieved by the client)
- session_attach() should check to see that the session exists

**Comment by erichanson** [comment]
Really, we should split out session into it's own thing.  It has other uses besides just events.

**Comment by micburks** [comment]
Another blocker is #15 .

Sessions should be created via API call and then attached to via websocket

Cannot currently call session.session_create() from API
