### ISSUE TITLE
ide: wetty integration?

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#155]
[wetty](https://github.com/krishnasrinivas/wetty) is a *very* nice web-based terminal.  Would be really cool to integrate this into Aquameta so superusers (and maybe regular users?) can get a db shell with the click of a button.  Problem is, it requires setting up a Linux username/password.  I managed to do a `chsh` to set `psql aquameta` as the login shell instead of `bash`.  It would be nice if install somehow setup a Linux user for the superuser as well, or reuse an existing one if they already have one setup.  With AWS (which uses `ubuntu` as the default login), setting up a `sudo` user for the administrator would be nice anyway.

Wetty is a `node` application, opens up port 3000 (by default) and you just browse to a URL, and enter username and password and you're in.

**Comment by atrooper** [comment]
Probably need an interface to LDAP or active directory. In the long term if aquameta applications must integrate within an enterprise network, it must permit an external user authentication method anyway. An internally managed user credential system is a non starter for most enterprise applications. User credentials may need further internal information on access type, are you a developer? or are you a user? The application may have additional levels of user types: can you administer the system? read only user? etc. These criteria will be established and managed by the application but the user list will come from an external directory.

Something like https://github.com/jeremycx/node-LDAP may do the trick, 

Looking at wetty more deeply, while it is a beautiful web-based terminal, developers can simply ssh to the host to get identical functionality. It is not clear that it adds a large value to the framework. 

I get the desire to have an integrated IDE, however the value of aquameta may be the speed at which applications can be deployed followed by a long term relationship with satisfied end users consuming the result.

**Comment by erichanson** [comment]
@atrooper Agree.  It might be nice for a cloud deployment SaaS, but it's not a core feature.
