### ISSUE TITLE
pg_roles.rolcatupdate does not exist

### ISSUE THREAD

**Issue by schinckel** [aquametalabs/aquameta#16]
<pre>
# \d pg_roles

              View "pg_catalog.pg_roles"
     Column     │           Type           │ Modifiers 
────────────────┼──────────────────────────┼───────────
 rolname        │ name                     │ 
 rolsuper       │ boolean                  │ 
 rolinherit     │ boolean                  │ 
 rolcreaterole  │ boolean                  │ 
 rolcreatedb    │ boolean                  │ 
 rolcanlogin    │ boolean                  │ 
 rolreplication │ boolean                  │ 
 rolconnlimit   │ integer                  │ 
 rolpassword    │ text                     │ 
 rolvaliduntil  │ timestamp with time zone │ 
 rolbypassrls   │ boolean                  │ 
 rolconfig      │ text[]                   │ 
 oid            │ oid                      │ 

</pre>

This is on postgres 9.5.0

**Comment by micburks** [comment]
Postgres did away with this column when upgrading to 9.5. The current aquameta build on master uses 9.4. Thanks for opening the issue, we'll have an upgrade soon!
