### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by manakill** [aquametalabs/aquameta#175]
I go to localhost and see the 3 options. I click on /dev/ and it says Forbidden
I click on /docs/ and it says Not Found -- also says that on /snake/

Maybe installer should check to make sure it's set up correctly at the end, it's probably something easy but I'm not a linux expert

**Comment by erichanson** [comment]
Hmm, did you download the rc5 release, or clone from master?  Also, when the installer ran, did you install bundles from source, or choose the online install?  I thought I replaced that page with something more helpful but will double check.

Regardless, browse to `/login` and authenticate, then things will work.

**Comment by erichanson** [comment]
Apparently that update didn't get pushed to the hub.  It's up there now.  If you go to your remotes tab, you can click "pull" on all the pull buttons (they take a few seconds to complete but it's working under the hood) and it will pull down the latest version of the IDE.  Then go into the IDE bundle, and under the "commits" tab, click "Checkout" at the latest one, to checkout that version.  Do the same for the semantics bundle, and you'll have the latest versions of everything.

**Comment by manakill** [comment]
Awesome, I'm logged in! I can't wait to play around later today. Seems like this can be a very powerful and customizable platform. (heard about on TwiT btw)
