### ISSUE TITLE
ERROR:  relation "endpoint.js_module" does not exist

### ISSUE THREAD

**Issue by T0astBread** [aquametalabs/aquameta#191]
Just tried installing aquameta but the installation script failed with the following error:
```
ERROR:  relation "endpoint.js_module" does not exist
CONTEXT:  SQL statement "alter table endpoint.js_module disable trigger all"
PL/pgSQL function bundle.checkout(uuid) line 87 at EXECUTE
```
All pages return a 403 Forbidden response (including `/login`). It is worth noting that this wasn't a clean install: I previously had an offline install that also only returned 403s so I re-downloaded the latest release (0.2.0-rc5) and tried a hub install. (#175 mentioned something including the hub so I assumed that would resolve the issue.)

**Comment by erichanson** [comment]
Ah crap yeah those releases won't work anymore.  Install from master and see if that helps?  I'll put out a current release.  Wasn't expecting to be on HN. :)

**Comment by T0astBread** [comment]
Alright I'll try the new release (on a clean host now), gimme a sec

**Comment by T0astBread** [comment]
Oh and before I forget it - during my last install I had to manually install llvm-6.0 beforehand I think? Otherwise I would run into an error much earlier. Is that normal?

**Comment by erichanson** [comment]
No that's not normal.  Are you using Ubuntu or Debian?

**Comment by T0astBread** [comment]
I'm using Ubuntu 19.04 inside an LXC container. The exact error looked like this:
```
installing plv8 binnnnnnnnnnnnnnnnaries!...................................
/home/t0astbread/aquameta/plv8-binaries/postgresql-11/plv8-2.3.11
./install-binaries-huzzah.sh: line 24: /usr/lib/llvm-6.0/bin/llvm-lto: No such file or directory
```

**Comment by erichanson** [comment]
Hmmm, hadn't run into that, usually llvm-6.0 comes installed at least in my experience.  Wonder what is different.

But I'll add it to the install script.  Thanks.

**Comment by T0astBread** [comment]
No problem! Also, I can happily report that the new rc6 release is working for me. I haven't tried out an offline install but the hub option runs. Thanks for helping me out!
