### ISSUE TITLE
JS and other assets 404 after install

### ISSUE THREAD

**Issue by gmerrall** [aquametalabs/aquameta#192]
After spotting aquameta via HN thought I'd give it a go.
Environment: Ubuntu Bionic (18.04) inside Vagrant/Virtualbox. I've mapped port 8080 on my machine to port 80 on the guest OS.

Selected Ubuntu repo install and download from bundle hub. Didn't see any errors go past but I did get pulled away at one point during install. Shell script appeared to complete and HTTP server + postgresql is running.

Visiting localhost:8080 on my machine loads the Aquameta home page but /system.js and content under /assets/ fails to load.

e.g. on host machine
```
curl http://localhost:8080/system.js
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /system.js HTTP/1.1
> Host: localhost:8080

< HTTP/1.1 404 NOT FOUND
< Date: Fri, 18 Oct 2019 05:14:44 GMT
< Server: aquameta

```
Same applies directly on the guest OS
```
curl -v http://localhost/system.js
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /system.js HTTP/1.1
> Host: localhost

< HTTP/1.1 404 NOT FOUND
< Date: Fri, 18 Oct 2019 05:15:53 GMT
< Server: aquameta
```

**Comment by erichanson** [comment]
During install did you choose the OPEN REGISTRATION or the PRIVATE one?  If you chose PRIVATE, things are *very* locked down and no pages will work (I believe even including the front page) until you login.  Try hitting `/login` and see if that brings up a login prompt?

**Comment by gmerrall** [comment]
You're correct in that I selected PRIVATE. Hit /login and was able to login with the credentials created during set up and the front page now loads correctly.

Would suggest you either allow the index to load correctly in private mode or modify the install script to prompt the user to hit /login when it's printing out the URLs at the end of the install

**Comment by erichanson** [comment]
Fixed.  Thanks.
