### ISSUE TITLE
Missing IP address in installation message

### ISSUE THREAD

**Issue by ar-jan** [aquametalabs/aquameta#199]
On Debian I got the below message with the correct ipv4 address for external link, but on Ubuntu 18.04 it looks like this:

> Aquameta was successfully installed.  Next, login and configure your installation:
> Localhost link: http://localhost/login
> Machine link:   http://127.0.1.1/login
> External link:  http:///login

I tried the `dig` command from Aquameta's installer plus a few others, and for some reason dig (on an Ubuntu VPS) doesn't return my IP address:

> root@web:/var/aquameta# dig +short myip.opendns.com @resolver1.opendns.com
> root@web:/var/aquameta# dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com
> "78.47.xx.xx"
> root@web:/var/aquameta# curl ipv4.icanhazip.com
> 78.47.xx.xx

I don't know if this is due to Ubuntu or some other reason.

**Comment by erichanson** [comment]
Hmmmm, yeah you may not have an external IP that dig can find.  The three URLs there are just kind of thrown up on the screen for convenience and may not necessarily apply to all scenarios.   There's really no way for the system to definitively know.  It's up to the user for the most part to know where they're installing it.  I supposed we could make the script not print empty URLs though.

**Comment by ar-jan** [comment]
I guess it's not that important, but it's strange because with the google service dig is able to detect the ip. And so is icanhazip.com.
