### ISSUE TITLE
Support file and directory resource from endpoint

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#22]
- create `endpoint.mimetype_extension` table
 - fields: `id`, `mimetype_id`, `extension` text
 - propagate tables with appropriate values from [some list](http://hul.harvard.edu/ois/systems/wax/wax-public-help/mimetypes.htm)
- create endpoint.resource_file table
 - fields: `id`, `file_id` referends `fsfdw.file` (no relational integrity possible here right?)
- create `endpoint.resource_directory` table
 - fields: `id`, `directory_id` referends `fsfdw.directory`, `indexes` boolean
 - `indexes` field determines whether the server serves up browsable html directory index, similar to the old [apache directive](https://wiki.apache.org/httpd/DirectoryListings)
- create a new uwsgi app (or possibly integrate into resource hosting app?)
 - looks at `resource_file` and `resource_directory` for matching paths
 - look at them *after* looking at of course endpoint as well as `resource_binary` and `resource_text`
 - skip over support for indexes field for now... we'll probably want to do that with widgets
 - for `resource_file`, try to find the appropriate mimetype to send as a header from `mimetype_extension` field
 - for `resource_directory`, accept any sub-paths of the requested directory that match a file's path

**Comment by micburks** [comment]
Page app  supports showing a single directory or a single file, but it needs the ability to mount a directory.  This could be done by recursively tracing the path to look for the most recent indexed directory

**Comment by micburks** [comment]
Filesystem foreign data wrapper needs to be installed from Dockerfile
