### ISSUE TITLE
expect URI encoded values in endpoint

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#23]
So our emerging URL pattern uses slashes as significant delimiters.  But postgresql schemas, tables, functions, columns, etc can contain slashes.  We need to encode literal values in the client using [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) and decode them on the server using `http_client.urlencode`.

**Comment by micburks** [comment]
The component that expects slashes to be significant are the casts from text to meta types, so I am putting the new url decode function in 000-meta_identifiers.sql

The server takes the encoded path and passes it into endpoint.request. The request function then uses the meta casts to create the correct type containing identifying strings
