### ISSUE TITLE
Question: Can Aquameta be injected inside something like Amazon RDS?

### ISSUE THREAD

**Issue by doublemarked** [aquametalabs/aquameta#44]
https://aws.amazon.com/rds/postgresql/

**Comment by erichanson** [comment]
We haven't tried getting it into RDS but it can certainly run on ec2 or their new Docker container hosting service.  Only problem with RDS that I can see is that I'm not sure they expose full customization of PostgreSQL, would need to check what features they support but I suspect we're pushing PostgreSQL further than they expose.  I'll check it out though and get back to you more definitively.

**Comment by erichanson** [comment]
No, but here's a script that will setup Aquameta on an ubuntu ec2:

https://bitbucket.org/aquameta/aquameta-aws
