### ISSUE TITLE
docker instructions fail

### ISSUE THREAD

**Issue by outofculture** [aquametalabs/aquameta#73]
$ docker build -t aquametalabs/aquameta
    "docker build" requires exactly 1 argument(s).
    See 'docker build --help'.

    Usage:  docker build [OPTIONS] PATH | URL | -

    Build an image from a Dockerfile

    $ docker --version
    Docker version 17.06.0-ce, build 02c1d87

I expect that command just needs a ` . ` at the end.

**Comment by erichanson** [comment]
Fixed via https://github.com/aquametalabs/aquameta/commit/4a091251a95d52a6a9ac78bdd7efec05c2c34a2f.  Thanks.
