### ISSUE TITLE
"New Widget" in debugger blacks out the page

### ISSUE THREAD

**Issue by outofculture** [aquametalabs/aquameta#74]
Maybe this is just a documentation issue, and this button only makes sense in other contexts, but
![here's what happens when I push the button](https://user-images.githubusercontent.com/28812/29531962-c53af6d0-865f-11e7-9e59-77e7f01e4852.gif).
The page either gets an overlay that obscures everything or the colors shift so as to be all black. Clicking anywhere exits this state.

**Comment by erichanson** [comment]
Yep that's broken.  You can use new row from the bundle manager instead for now.

**Comment by erichanson** [comment]
Ok via https://github.com/aquametalabs/aquameta/commit/f50f959d66224ebc2e4e26256574aaacb034eb00 the new widget link has been removed, since it really doesn't make sense outside the context of a bundle, and a app usually contains more than one bundle.  Also some other debugger fixes.
