### ISSUE TITLE
support permissions, RLS in meta

### ISSUE THREAD

**Issue by erichanson** [aquametalabs/aquameta#9]
We need to datify permissions and RLS so we can build a nice RLS editor GUI etc.  We already have meta.role, which has good coverage of the `ALTER ROLE` grammar.  RLS will fk to meta.role.  Some design work to do here.

**Comment by erichanson** [comment]
for starters, create meta.role_inheritence

**Comment by erichanson** [comment]
RLS for meta looks like:

type siuda for enum, possible values { select, insert, update, delete, all }
type policy_id (name, meta.relation_id)

policy view:
- id policy_id
- name
- table_name
- command siuda
- using text
- check text

policy_role view:
- policy_id
- role_id

**Comment by micburks** [comment]
could use grant on database, schema, column, etc. but not necessary right now. closing
